#!/usr/bin/env bash
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root: sudo $0 [config-file]" >&2
  exit 1
fi

CONFIG_FILE="${1:-./config.local}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ ! -f "${CONFIG_FILE}" ]]; then
  echo "Config file not found: ${CONFIG_FILE}" >&2
  echo "Copy config.example to config.local and edit it first." >&2
  exit 1
fi

# shellcheck disable=SC1090
source "${CONFIG_FILE}"

DEVICE_NAME="${DEVICE_NAME:-Canton RC-L}"
USB_DAC_MATCH="${USB_DAC_MATCH:-}"
ALSA_DEVICE="${ALSA_DEVICE:-}"
LIBRESPOT_BITRATE="${LIBRESPOT_BITRATE:-320}"
LIBRESPOT_FORMAT="${LIBRESPOT_FORMAT:-S16}"
LIBRESPOT_INITIAL_VOLUME="${LIBRESPOT_INITIAL_VOLUME:-100}"
LIBRESPOT_VOLUME_CTRL="${LIBRESPOT_VOLUME_CTRL:-fixed}"
LIBRESPOT_VOLUME_NORMALISATION="${LIBRESPOT_VOLUME_NORMALISATION:-no}"
WEB_HOST="${WEB_HOST:-127.0.0.1}"
WEB_PORT="${WEB_PORT:-3000}"
APP_DIR="${APP_DIR:-/opt/spotify-now-playing}"
APP_USER="${APP_USER:-spotify-now-playing}"
ENV_FILE="${ENV_FILE:-/etc/spotify-now-playing.env}"
INSTALL_KIOSK="${INSTALL_KIOSK:-yes}"
KIOSK_USER="${KIOSK_USER:-${SUDO_USER:-pi}}"
KIOSK_URL="${KIOSK_URL:-http://localhost:3000}"
INSTALL_MINIMAL_GUI_IF_MISSING="${INSTALL_MINIMAL_GUI_IF_MISSING:-yes}"
DISABLE_SCREEN_BLANKING="${DISABLE_SCREEN_BLANKING:-yes}"

run() {
  echo "+ $*"
  "$@"
}

render_template() {
  local src="$1"
  local dest="$2"
  sed \
    -e "s#@APP_USER@#${APP_USER}#g" \
    -e "s#@APP_DIR@#${APP_DIR}#g" \
    -e "s#@ENV_FILE@#${ENV_FILE}#g" \
    -e "s#@WEB_HOST@#${WEB_HOST}#g" \
    -e "s#@WEB_PORT@#${WEB_PORT}#g" \
    -e "s#@KIOSK_USER@#${KIOSK_USER}#g" \
    -e "s#@KIOSK_URL@#${KIOSK_URL}#g" \
    "${src}" > "${dest}"
}

detect_alsa_device() {
  if [[ -n "${ALSA_DEVICE}" ]]; then
    echo "${ALSA_DEVICE}"
    return
  fi

  if [[ -z "${USB_DAC_MATCH}" ]]; then
    echo "ALSA_DEVICE is empty and USB_DAC_MATCH is not set." >&2
    exit 1
  fi

  local card_id
  card_id="$(awk -v needle="${USB_DAC_MATCH}" '
    BEGIN { IGNORECASE = 1 }
    /^[[:space:]]*[0-9]+[[:space:]]+\[/ {
      line = $0
      getline desc
      if (line ~ needle || desc ~ needle) {
        sub(/^.*\[/, "", line)
        sub(/\].*$/, "", line)
        gsub(/[[:space:]]+$/, "", line)
        print line
        exit
      }
    }
  ' /proc/asound/cards || true)"

  if [[ -z "${card_id}" ]]; then
    echo "Could not detect USB DAC matching: ${USB_DAC_MATCH}" >&2
    echo "Connected playback devices:" >&2
    aplay -l >&2 || true
    exit 1
  fi

  echo "hw:CARD=${card_id},DEV=0"
}

install_base_packages() {
  run apt-get update
  run apt-get -y install \
    alsa-utils \
    ca-certificates \
    curl \
    gnupg \
    rsync \
    python3-fastapi \
    python3-httpx \
    python3-dotenv \
    python3-uvicorn
}

install_raspotify() {
  if ! dpkg-query -W raspotify >/dev/null 2>&1; then
    echo "+ curl -sL https://dtcooper.github.io/raspotify/install.sh | sh"
    curl -sL https://dtcooper.github.io/raspotify/install.sh | sh
  fi
}

configure_raspotify() {
  local device="$1"

  if [[ -f /etc/raspotify/conf && ! -f /etc/raspotify/conf.before-spotify-streamer ]]; then
    run cp -a /etc/raspotify/conf /etc/raspotify/conf.before-spotify-streamer
  fi

  cat > /etc/raspotify/conf <<EOF
# /etc/raspotify/conf -- arguments/configuration for librespot
# Generated by raspberry-spotify-streamer.

LIBRESPOT_NAME="${DEVICE_NAME}"
LIBRESPOT_DEVICE_TYPE="speaker"
LIBRESPOT_BACKEND="alsa"
LIBRESPOT_DEVICE="${device}"
LIBRESPOT_BITRATE="${LIBRESPOT_BITRATE}"
LIBRESPOT_FORMAT="${LIBRESPOT_FORMAT}"
LIBRESPOT_MIXER_TYPE="softvol"
LIBRESPOT_INITIAL_VOLUME="${LIBRESPOT_INITIAL_VOLUME}"
LIBRESPOT_VOLUME_CTRL="${LIBRESPOT_VOLUME_CTRL}"
LIBRESPOT_DISABLE_AUDIO_CACHE=
LIBRESPOT_DISABLE_CREDENTIAL_CACHE=
LIBRESPOT_QUIET=
TMPDIR=/tmp
EOF

  if [[ "${LIBRESPOT_VOLUME_NORMALISATION}" == "yes" ]]; then
    echo "LIBRESPOT_ENABLE_VOLUME_NORMALISATION=" >> /etc/raspotify/conf
  fi

  run systemctl daemon-reload
  run systemctl enable raspotify
  run systemctl restart raspotify
}

install_web_app() {
  if ! id "${APP_USER}" >/dev/null 2>&1; then
    run useradd --system --home-dir "${APP_DIR}" --shell /usr/sbin/nologin "${APP_USER}"
  fi

  run mkdir -p "${APP_DIR}"
  run rsync -a --delete "${REPO_DIR}/app/" "${APP_DIR}/app/"
  run install -m 0755 "${REPO_DIR}/scripts/get_refresh_token.py" "${APP_DIR}/get_refresh_token.py"
  run chown -R "${APP_USER}:${APP_USER}" "${APP_DIR}"

  if [[ ! -f "${ENV_FILE}" ]]; then
    install -m 0600 -o root -g root /dev/null "${ENV_FILE}"
    {
      printf 'SPOTIFY_CLIENT_ID="%s"\n' "${SPOTIFY_CLIENT_ID:-}"
      printf 'SPOTIFY_CLIENT_SECRET="%s"\n' "${SPOTIFY_CLIENT_SECRET:-}"
      printf 'SPOTIFY_REFRESH_TOKEN="%s"\n' "${SPOTIFY_REFRESH_TOKEN:-}"
    } > "${ENV_FILE}"
  fi
  run chown root:root "${ENV_FILE}"
  run chmod 600 "${ENV_FILE}"

  render_template "${REPO_DIR}/systemd/spotify-now-playing.service.in" /etc/systemd/system/spotify-now-playing.service
  run systemctl daemon-reload
  run systemctl enable --now spotify-now-playing.service
}

install_kiosk() {
  [[ "${INSTALL_KIOSK}" == "yes" ]] || return 0

  if ! id "${KIOSK_USER}" >/dev/null 2>&1; then
    echo "KIOSK_USER does not exist: ${KIOSK_USER}" >&2
    exit 1
  fi

  if ! command -v chromium >/dev/null 2>&1 || ! command -v labwc >/dev/null 2>&1 || ! command -v dbus-run-session >/dev/null 2>&1; then
    if [[ "${INSTALL_MINIMAL_GUI_IF_MISSING}" != "yes" ]]; then
      echo "Required kiosk packages are missing and INSTALL_MINIMAL_GUI_IF_MISSING is not yes." >&2
      exit 1
    fi
    run apt-get -y install chromium labwc xwayland dbus-x11 x11-xserver-utils wlopm
  fi

  run install -m 0755 "${REPO_DIR}/scripts/spotify-now-playing-kiosk" /usr/local/bin/spotify-now-playing-kiosk
  run usermod -aG audio,video,input,render "${KIOSK_USER}" || true

  local home
  home="$(getent passwd "${KIOSK_USER}" | cut -d: -f6)"
  run mkdir -p "${home}/.config/labwc"

  if [[ -f /etc/xdg/labwc/autostart && ! -f "${home}/.config/labwc/autostart" ]]; then
    run cp /etc/xdg/labwc/autostart "${home}/.config/labwc/autostart"
  fi

  if ! grep -q "spotify-now-playing-kiosk" "${home}/.config/labwc/autostart" 2>/dev/null; then
    cat >> "${home}/.config/labwc/autostart" <<EOF

# Spotify Now Playing kiosk
/usr/bin/xset s off -dpms 2>/dev/null || true
/usr/bin/wlopm --on '*' 2>/dev/null || true
KIOSK_URL="${KIOSK_URL}" /usr/local/bin/spotify-now-playing-kiosk &
EOF
  fi
  run chown -R "${KIOSK_USER}:${KIOSK_USER}" "${home}/.config/labwc"
  run chmod 755 "${home}/.config/labwc/autostart"

  if ! pgrep -u "${KIOSK_USER}" -x labwc >/dev/null 2>&1 && [[ "${INSTALL_MINIMAL_GUI_IF_MISSING}" == "yes" ]]; then
    render_template "${REPO_DIR}/systemd/spotify-kiosk.service.in" /etc/systemd/system/spotify-kiosk.service
    run systemctl daemon-reload
    run systemctl enable --now spotify-kiosk.service
  fi

  if [[ "${DISABLE_SCREEN_BLANKING}" == "yes" ]] && command -v raspi-config >/dev/null 2>&1; then
    run raspi-config nonint do_blanking 1 || true
  fi
}

main() {
  echo "Inspecting system..."
  cat /etc/os-release || true
  uname -m
  command -v systemctl >/dev/null
  command -v aplay >/dev/null || true
  aplay -l || true

  install_base_packages
  local detected_device
  detected_device="$(detect_alsa_device)"
  echo "Using ALSA output: ${detected_device}"

  install_raspotify
  configure_raspotify "${detected_device}"
  install_web_app
  install_kiosk

  echo
  echo "Installation complete."
  echo "Raspotify: $(systemctl is-active raspotify || true)"
  echo "Now Playing UI: $(systemctl is-active spotify-now-playing.service || true)"
  echo "Local UI: http://${WEB_HOST}:${WEB_PORT}"
  echo "Spotify Connect device: ${DEVICE_NAME}"
  echo "ALSA output: ${detected_device}"
  echo
  echo "If Spotify metadata or controls are not configured yet, run:"
  echo "  sudo ${APP_DIR}/get_refresh_token.py"
}

main "$@"
